### PR TITLE
Add checks on arc3 files

### PR DESCRIPTION
**Pull request by jeanconn**
Add checks on arc3 files

### CODE REVIEW

**Comment by jeanconn** [comment]
I should probably have just merged #22 as it is duplicated here.

**Comment by taldcroft** [comment]
I guess I don't understand why you are duplicating arc => arc3 checking instead of promoting the Ska3 arc to flight and have it writing to arc/.  Maybe I missed something in the plan.

**Comment by jeanconn** [comment]
I didn't have anything autonomously monitoring arc3 during this soak interval.  I figured a more conservative approach was to do this monitoring for a additional week and then promote.

And for promotion, I hadn't really decided if it made sense to write to arc (via symlink or code changes) or if it made sense to have arc/index.html redirect to arc3/index.html .

**Comment by jeanconn** [comment]
I suppose that I did have the autonomous monitoring of just the email warns from the cron task being basically fine over the interval.  

I suppose this PR could just be used for the test outputs I just made.  They show that all the right files are up-to-date now in the arc3 area consistent with expectations.  Combined with the reasonable errors / warnings in the logs that seems like enough for FD approval to promote.

**Comment by jeanconn** [comment]
OBE

**Pull request closed without merging**
